import assert from 'node:assert/strict';
import { state } from '../js/state.js';
import { captureInbox, routeInboxToKnowledge, createTaskFromKnowledge, updateKnowledge, updateTask, deleteTask, revertInboxRoute } from '../js/core/commands.js';
import { queryKnowledge, materialActions } from '../js/features/knowledge/model.js';
import { loadState, prepareState } from '../js/storage.js';
import adapter from '../js/storageAdapter.js';
const store=new Map();
globalThis.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
state.domains=[{id:'d1',title:'Дом'},{id:'d2',title:'Дача'}];
state.projects=[{id:'p1',domainId:'d2',title:'Сад'}];
const [source]=captureInbox('Тень в саду\nПосадить деревья рядом с террасой',{itemType:'thought',splitLines:false});
const {material}=routeInboxToKnowledge(source.id,{projectId:'p1'});
const snapshot=JSON.stringify(material), raw=source.rawText;
assert.throws(()=>updateKnowledge(material.id,{text:'Stale edit'},{expectedUpdatedAt:material.updatedAt-1}));
assert.equal(JSON.stringify(material),snapshot);
const task=createTaskFromKnowledge(material.id,{title:'Выбрать дерево',status:'today'});
assert.equal(task.projectId,'p1'); assert.equal(task.sourceKnowledgeId,material.id);
assert.equal(task.sourceInboxId,undefined);
assert.throws(()=>prepareState(JSON.stringify({...state, schema:8, knowledge:[]})));
assert.equal(JSON.stringify(material),snapshot); assert.equal(source.rawText,raw);
assert.equal(state.operationLog.at(-1).payload.sourceKnowledgeId,material.id);
assert.equal(revertInboxRoute(source.id).reason,'knowledge-has-tasks');
assert.equal(queryKnowledge(state,{query:'Дача деревья'}).length,1);
assert.equal(queryKnowledge(state,{kind:'note'}).length,0);
assert.equal(queryKnowledge(state,{domain:'d1'}).length,0);
assert.equal(queryKnowledge(state,{domain:'d2'}).length,1);
updateTask(task.id,{status:'done'});
loadState(); assert.equal(materialActions(state,material.id)[0].status,'done');
const before=JSON.stringify(state), save=adapter.save, warn=console.warn;
adapter.save=()=>{throw new Error('disk full');}; console.warn=()=>{};
assert.throws(()=>createTaskFromKnowledge(material.id,{title:'Failure'}),/disk full/);
adapter.save=save;console.warn=warn;assert.equal(JSON.stringify(state),before);
assert.throws(()=>createTaskFromKnowledge('missing',{title:'No source'}));
assert.throws(()=>createTaskFromKnowledge(material.id,{title:'No destination',projectId:null,domainId:null}));
deleteTask(task.id); assert.equal(materialActions(state,material.id).length,0);
assert(revertInboxRoute(source.id)); assert.equal(state.knowledge.length,0);
console.log('Knowledge actions: stable material/source, inherited placement, action provenance, query filters, reload, safe revert, deletion and failed persistence passed.');
